### ISSUE TITLE
Crash on Set

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#1406]
While running a test for the Python client, latest server on `develop`: https://github.com/pilosa/pilosa/commit/c1f11d40e43649e658b73c4b859263ae5e734492 crashed with the following traceback:
```
2018/06/22 23:23:29 PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 705 [running]:
runtime/debug.Stack(0xc420176e00, 0x1f4, 0xf8f280)
	/home/yuce/go/src/runtime/debug/stack.go:24 +0xa7
github.com/pilosa/pilosa/http.(*Handler).ServeHTTP.func1(0xc35940, 0xc420176e00, 0xc4201aa780)
	/home/yuce/Work/pilosa/server/src/github.com/pilosa/pilosa/http/handler.go:222 +0x91
panic(0xade1a0, 0xf8f280)
	/home/yuce/go/src/runtime/panic.go:502 +0x229
github.com/pilosa/pilosa.(*Field).Keys(0x0, 0xc42025a100)
	/home/yuce/Work/pilosa/server/src/github.com/pilosa/pilosa/field.go:387 +0x27
github.com/pilosa/pilosa.(*Executor).translateCall(0xc42019ee40, 0xc4203cb8fc, 0xa, 0xc42024bae0, 0xc4201a1e00, 0x3, 0x0)
	/home/yuce/Work/pilosa/server/src/github.com/pilosa/pilosa/executor.go:1621 +0x1bd
github.com/pilosa/pilosa.(*Executor).Execute(0xc42019ee40, 0xc364c0, 0xc4201a1890, 0xc4203cb8fc, 0xa, 0xc420552390, 0x0, 0x0, 0x0, 0xc420498f08, ...)
	/home/yuce/Work/pilosa/server/src/github.com/pilosa/pilosa/executor.go:106 +0x148
github.com/pilosa/pilosa.(*API).Query(0xc420219e30, 0xc364c0, 0xc4201a1890, 0xc4205da940, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/yuce/Work/pilosa/server/src/github.com/pilosa/pilosa/api.go:105 +0x21a
github.com/pilosa/pilosa/http.(*Handler).handlePostQuery(0xc4201aa780, 0xc35940, 0xc420176e00, 0xc420178a00)
	/home/yuce/Work/pilosa/server/src/github.com/pilosa/pilosa/http/handler.go:340 +0x218
github.com/pilosa/pilosa/http.(*Handler).(github.com/pilosa/pilosa/http.handlePostQuery)-fm(0xc35940, 0xc420176e00, 0xc420178a00)
	/home/yuce/Work/pilosa/server/src/github.com/pilosa/pilosa/http/handler.go:198 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4202b46f0, 0xc35940, 0xc420176e00, 0xc420178a00)
	/home/yuce/go/src/net/http/server.go:1947 +0x44
github.com/pilosa/pilosa/http.(*Handler).queryArgValidator.func1(0xc35940, 0xc420176e00, 0xc420178a00)
	/home/yuce/Work/pilosa/server/src/github.com/pilosa/pilosa/http/handler.go:159 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc4201218a0, 0xc35940, 0xc420176e00, 0xc420178a00)
	/home/yuce/go/src/net/http/server.go:1947 +0x44
github.com/pilosa/pilosa/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420219ea0, 0xc35940, 0xc420176e00, 0xc420178a00)
	/home/yuce/Work/pilosa/server/src/github.com/pilosa/pilosa/vendor/github.com/gorilla/mux/mux.go:159 +0xed
github.com/pilosa/pilosa/vendor/github.com/gorilla/handlers.(*cors).ServeHTTP(0xc42028fc20, 0xc35940, 0xc420176e00, 0xc420178800)
	/home/yuce/Work/pilosa/server/src/github.com/pilosa/pilosa/vendor/github.com/gorilla/handlers/cors.go:51 +0xa04
github.com/pilosa/pilosa/http.(*Handler).ServeHTTP(0xc4201aa780, 0xc35940, 0xc420176e00, 0xc420178800)
	/home/yuce/Work/pilosa/server/src/github.com/pilosa/pilosa/http/handler.go:230 +0xde
net/http.serverHandler.ServeHTTP(0xc4201b5ad0, 0xc35940, 0xc420176e00, 0xc420178800)
	/home/yuce/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420298140, 0xc36400, 0xc4205da800)
	/home/yuce/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/home/yuce/go/src/net/http/server.go:2795 +0x27b
```
The client test that crashed the server ran the following code:
```python
client.query(self.index.batch_query(
            field.set(10, 5),
            field.set(10, 10),
            field.set(10, 15),
            field.set(20, 5),
           field.set(30, 5)))
```
Didn't yet look into the cause of the crash. Will updated with my findings.

**Comment by yuce** [comment]
Closing. Fixed in https://github.com/pilosa/pilosa/tree/wip-api-refactor
