### ISSUE TITLE
Calling GroupBy(Rows()) crash the server

### ISSUE THREAD

**Issue by WaaX** [pilosa/pilosa#1800]
### Expected behavior
Server return an error

### Actual behavior
Server crash

### Steps to reproduce the behavior
curl localhost:10101/index/patients/query -X POST -d 'GroupBy(Rows())'

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
MacBook Pro (Retina, 15-inch, Mid 2014), 2.5 GHz Intel Core i7, 16 GB 1600 MHz DDR3

**Comment by jaffee** [comment]
this is easily reproduced on 1.2

```
panic: interface conversion: interface {} is nil, not string

goroutine 150 [running]:
github.com/pilosa/pilosa.newGroupByIterator(0xc006795120, 0x1, 0x1, 0xc0067920e0, 0x1, 0x1, 0x0, 0xc0067a615c, 0xa, 0x3, ...)
	/Users/jaffee/go/src/github.com/pilosa/pilosa/executor.go:2764 +0x998
github.com/pilosa/pilosa.(*executor).executeGroupByShard(0xc0000c6d40, 0x4a26ee0, 0xc006779c50, 0xc0067a615c, 0xa, 0xc0067797d0, 0x0, 0x3, 0xc006795120, 0x1, ...)
	/Users/jaffee/go/src/github.com/pilosa/pilosa/executor.go:1064 +0xcf
github.com/pilosa/pilosa.(*executor).executeGroupBy.func1(0x3, 0x0, 0x0, 0x0, 0x0)
	/Users/jaffee/go/src/github.com/pilosa/pilosa/executor.go:943 +0x9a
github.com/pilosa/pilosa.(*executor).mapperLocal.func1(0xc000252660, 0xc0002803d0, 0xc0002526c0, 0x3)
	/Users/jaffee/go/src/github.com/pilosa/pilosa/executor.go:2291 +0x48
created by github.com/pilosa/pilosa.(*executor).mapperLocal
	/Users/jaffee/go/src/github.com/pilosa/pilosa/executor.go:2290 +0x175
panic: interface conversion: interface {} is nil, not string

goroutine 149 [running]:
github.com/pilosa/pilosa.newGroupByIterator(0xc006795120, 0x1, 0x1, 0xc0067920e0, 0x1, 0x1, 0x0, 0xc0067a615c, 0xa, 0x2, ...)
	/Users/jaffee/go/src/github.com/pilosa/pilosa/executor.go:2764 +0x998
github.com/pilosa/pilosa.(*executor).executeGroupByShard(0xc0000c6d40, 0x4a26ee0, 0xc006779c50, 0xc0067a615c, 0xa, 0xc0067797d0, 0x0, 0x2, 0xc006795120, 0x1, ...)
	/Users/jaffee/go/src/github.com/pilosa/pilosa/executor.go:1064 +0xcf
github.com/pilosa/pilosa.(*executor).executeGroupBy.func1(0x2, 0x0, 0x0, 0x0, 0x0)
	/Users/jaffee/go/src/github.com/pilosa/pilosa/executor.go:943 +0x9a
github.com/pilosa/pilosa.(*executor).mapperLocal.func1(0xc000252660, 0xc0002803d0, 0xc0002526c0, 0x2)
	/Users/jaffee/go/src/github.com/pilosa/pilosa/executor.go:2291 +0x48
created by github.com/pilosa/pilosa.(*executor).mapperLocal
	/Users/jaffee/go/src/github.com/pilosa/pilosa/executor.go:2290 +0x175
```

Interestingly, the `Rows` call must be inside `GroupBy` - if not we get the proper error: "argument required: field"
