### ISSUE TITLE
Panic in TranslateStore - TranslateColumnsToUint64

### ISSUE THREAD

**Issue by dmibor** [pilosa/pilosa#2075]
Stumbled upon a weird panic - thought maybe would be useful

### What's going wrong?
Running `BenchmarkTranslateFile_TranslateColumnsToUint64` with `const batchSize = 10000000`
ends up with a weird looking panic
```
goos: darwin
goarch: amd64
pkg: github.com/pilosa/pilosa
BenchmarkTranslateFile_TranslateColumnsToUint64-8       panic: runtime error: slice bounds out of range [134217749:134217728]

goroutine 8644 [running]:
github.com/pilosa/pilosa.(*index).lookupKey(0xc000474360, 0x8000015, 0x2aa156bea, 0x10, 0x36a5416)
        /Users/dim/GoglandProjects/src/github.com/pilosa/pilosa/translate.go:997 +0xf9
github.com/pilosa/pilosa.(*index).insertIDbyOffset(0xc000474360, 0x8000015, 0x630f44, 0xc118c4bd30)
        /Users/dim/GoglandProjects/src/github.com/pilosa/pilosa/translate.go:963 +0x39
github.com/pilosa/pilosa.(*index).insert(0xc000474360, 0x630f44, 0x8000015)
        /Users/dim/GoglandProjects/src/github.com/pilosa/pilosa/translate.go:956 +0x170
github.com/pilosa/pilosa.(*TranslateFile).applyEntry(0xc00035dd10, 0xc0006b8c18, 0x8000011, 0xc641812, 0x0)
        /Users/dim/GoglandProjects/src/github.com/pilosa/pilosa/translate.go:339 +0x21a
github.com/pilosa/pilosa.(*TranslateFile).appendEntry(0xc00035dd10, 0xc0006b8c18, 0x10, 0xc135e33210)
        /Users/dim/GoglandProjects/src/github.com/pilosa/pilosa/translate.go:304 +0xbf
github.com/pilosa/pilosa.(*TranslateFile).TranslateColumnsToUint64(0xc00035dd10, 0x4a09bd3, 0x4, 0xc0119fa000, 0x989680, 0x989680, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/dim/GoglandProjects/src/github.com/pilosa/pilosa/translate.go:579 +0x7fa
github.com/pilosa/pilosa_test.BenchmarkTranslateFile_TranslateColumnsToUint64(0xc0001ee700)
        /Users/dim/GoglandProjects/src/github.com/pilosa/pilosa/translate_test.go:968 +0x42b
testing.(*B).runN(0xc0001ee700, 0x5f5e100)
        /usr/local/opt/go/libexec/src/testing/benchmark.go:190 +0xcc
testing.(*B).launch(0xc0001ee700)
        /usr/local/opt/go/libexec/src/testing/benchmark.go:320 +0x10c
created by testing.(*B).doBench
        /usr/local/opt/go/libexec/src/testing/benchmark.go:275 +0x55
exit status 2
FAIL    github.com/pilosa/pilosa        139.136s
```

### What was expected?
translating keys does not panic
### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

**Comment by dmibor** [comment]
looks like nothing serious, just batchsize issue, closing
