### ISSUE TITLE
panic in RLE branch while importing taxi data

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#713]
```
Pilosa v0.4.0-119-g230f419, build time 2017-07-07T15:44:50+0000
Using data from: /home/ubuntu/pilosa/data1
Listening as http://node0.testrle1.sandbox.pilosa.com:10101
2017/07/07 16:45:46 http: panic serving 10.0.1.176:46578: runtime error: index out of range
goroutine 2144 [running]:
net/http.(*conn).serve.func1(0xc420218000)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xab6860, 0xeba2c0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/pilosa/pilosa/roaring.(*container).arrayToBitmap(0xc432356000)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/roaring/roaring.go:1466 +0x13f
github.com/pilosa/pilosa/roaring.(*container).arrayAdd(0xc432356000, 0xc4000084b9, 0xc4201cd501)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/roaring/roaring.go:1178 +0x8da
github.com/pilosa/pilosa/roaring.(*container).add(0xc432356000, 0x84b9, 0x300)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/roaring/roaring.go:1150 +0xaf
github.com/pilosa/pilosa/roaring.(*Bitmap).add(0xc4315fe410, 0x12484b9, 0xc450b2ef01)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/roaring/roaring.go:133 +0x91
github.com/pilosa/pilosa/roaring.(*op).apply(0xc450b2efa0, 0xc4315fe410, 0x0)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/roaring/roaring.go:2826 +0x12f
github.com/pilosa/pilosa/roaring.(*Bitmap).Add(0xc4315fe410, 0xc450b2f028, 0x1, 0x1, 0x3f1a36e2eb1c432d, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/roaring/roaring.go:114 +0x97
github.com/pilosa/pilosa.(*Fragment).Import.func1(0xc47dede000, 0x7d8c0, 0x8e000, 0xc42f5ea000, 0x7d8c0, 0x8e000, 0xc4302da100, 0xc450b2f180, 0xc42039b380, 0xb95cc0)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/fragment.go:964 +0x19a
github.com/pilosa/pilosa.(*Fragment).Import(0xc4302da100, 0xc47dede000, 0x7d8c0, 0x8e000, 0xc42f5ea000, 0x7d8c0, 0x8e000, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/fragment.go:992 +0x12a
github.com/pilosa/pilosa.(*Frame).Import(0xc420298370, 0xc4587d2000, 0x7d8c0, 0x8e000, 0xc42aed2000, 0x7d8c0, 0x8e000, 0xc447a3a000, 0x7d8c0, 0x7d8c0, ...)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/frame.go:598 +0x8f7
github.com/pilosa/pilosa.(*Handler).handlePostImport(0xc420199340, 0xe86e80, 0xc4238360e0, 0xc432103400)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/handler.go:1028 +0x638
github.com/pilosa/pilosa.(*Handler).(github.com/pilosa/pilosa.handlePostImport)-fm(0xe86e80, 0xc4238360e0, 0xc432103400)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/handler.go:119 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4201e0ab0, 0xe86e80, 0xc4238360e0, 0xc432103400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/pilosa/pilosa/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420057400, 0xe86e80, 0xc4238360e0, 0xc432103400)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
github.com/pilosa/pilosa.(*Handler).ServeHTTP(0xc420199340, 0xe86e80, 0xc4238360e0, 0xc432103100)
	/home/ubuntu/go/src/github.com/pilosa/pilosa/handler.go:142 +0x91
net/http.serverHandler.ServeHTTP(0xc42028e000, 0xe86e80, 0xc4238360e0, 0xc432103100)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420218000, 0xe87b80, 0xc42196a080)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by alanbernstein** [comment]
Note: `probably hiding some ugly bug but it prevents a crash` at line 1441, which is very similar logic as 1466. @tgruben any insight?

**Comment by tgruben** [comment]
In order for that crash to occur the value (v) has to be > 1024.  I'm not seeing how that is possible, but the crash happened to there must be path

**Comment by jaffee** [comment]
@tgruben `v` in the code needs to be >= to `0xFFFF + 1` - i.e. `int(v)/64 >= 1024`

`bitmap.Add` always calls `lowbits` (which masks the value with `0xFFFF` before doing `container.add` so it's difficult to see how this could happen.

My current theory is that there is a bug in `container.runAdd` which adds the wrong value in some cases - then it gets converted to an array container, then it tries to get converted to a bitmap container. 

I've not yet been able to reproduce this, either in a test, or importing taxi data. I'm going to try writing some fuzzers to see if I can smoke it out.

**Comment by alanbernstein** [comment]
@jaffee I'm hoping recent work covered this, but I'd like to verify. If I can import taxi data without crashing, do you think that's a good indication this is fixed?

**Comment by jaffee** [comment]
Let's do full taxi + elevation + weather and hit it with some queries. If that is all handled stably, I'd be fairly confident
