### ISSUE TITLE
Crash: "unexpected fault" in bitmap.clone

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#918]
### Expected behavior
No error.

### Actual behavior
Following stacktrace is observed:
```
unexpected fault address 0x7fc092c995aa
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fc092c995aa pc=0x45d27f]
goroutine 7145745 [running]:
runtime.throw(0xb9f8f3, 0x5)
    /usr/local/Cellar/go/1.9.1/libexec/src/runtime/panic.go:605 +0x95 fp=0xc4363610a0 sp=0xc436361080 pc=0x42b935
runtime.sigpanic()
    /usr/local/Cellar/go/1.9.1/libexec/src/runtime/signal_unix.go:374 +0x227 fp=0xc4363610f0 sp=0xc4363610a0 pc=0x442637
runtime.memmove(0xc462339ca8, 0x7fc092c995aa, 0x8)
    /usr/local/Cellar/go/1.9.1/libexec/src/runtime/memmove_amd64.s:168 +0x12f fp=0xc4363610f8 sp=0xc4363610f0 pc=0x45d27f
github.com/pilosa/pilosa/roaring.(*container).clone(...)
    /Users/cody/go/src/github.com/pilosa/pilosa/roaring/roaring.go:1619
github.com/pilosa/pilosa/roaring.(*Bitmap).Clone(0xc4444d7f90, 0x600000)
    /Users/cody/go/src/github.com/pilosa/pilosa/roaring/roaring.go:96 +0x42f fp=0xc4363611a0 sp=0xc4363610f8 pc=0x63f88f
github.com/pilosa/pilosa.(*Fragment).row(0xc427a16ea0, 0x1469cde, 0x101, 0x1)
    /Users/cody/go/src/github.com/pilosa/pilosa/fragment.go:370 +0x79 fp=0xc4363611f0 sp=0xc4363611a0 pc=0x846939
github.com/pilosa/pilosa.(*Fragment).setBit(0xc427a16ea0, 0x1469cde, 0x6991b8, 0xc427a16ea0, 0x0, 0x0)
    /Users/cody/go/src/github.com/pilosa/pilosa/fragment.go:419 +0x16d fp=0xc436361260 sp=0xc4363611f0 pc=0x846d7d
github.com/pilosa/pilosa.(*Fragment).SetBit(0xc427a16ea0, 0x1469cde, 0x6991b8, 0x0, 0x0, 0x0)
    /Users/cody/go/src/github.com/pilosa/pilosa/fragment.go:389 +0x90 fp=0xc4363612a0 sp=0xc436361260 pc=0x846bc0
github.com/pilosa/pilosa.(*View).SetBit(0xc420f30600, 0x1469cde, 0x6991b8, 0xc420f30600, 0x0, 0x0)
    /Users/cody/go/src/github.com/pilosa/pilosa/view.go:273 +0x87 fp=0xc4363612e0 sp=0xc4363612a0 pc=0x884cf7
github.com/pilosa/pilosa.(*Frame).SetBit(0xc420369040, 0xba2bee, 0x8, 0x1469cde, 0x6991b8, 0x0, 0x2, 0xc4a8cc474c, 0xc4363613f0)
    /Users/cody/go/src/github.com/pilosa/pilosa/frame.go:616 +0xb4 fp=0xc436361360 sp=0xc4363612e0 pc=0x853fb4
github.com/pilosa/pilosa.(*Executor).executeSetBitView(0xc430198060, 0xf38ae0, 0xc48551d080, 0xc4a8cc474c, 0x4, 0xc48551d230, 0xc420369040, 0xba2bee, 0x8, 0x6991b8, ...)
    /Users/cody/go/src/github.com/pilosa/pilosa/executor.go:1063 +0x35c fp=0xc436361438 sp=0xc436361360 pc=0x8401bc
github.com/pilosa/pilosa.(*Executor).executeSetBit(0xc430198060, 0xf38ae0, 0xc48551d080, 0xc4a8cc474c, 0x4, 0xc48551d230, 0xc462339944, 0xc4363616e8, 0x410947, 0xc47da22ac0)
    /Users/cody/go/src/github.com/pilosa/pilosa/executor.go:1036 +0x79e fp=0xc436361608 sp=0xc436361438 pc=0x83f8be
... TRUNCATED
```

### Steps to reproduce the behavior
Unknown - see environment info.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
6 (big)node Pilosa cluster with replication factor of 2. v0.7.1
Lots of concurrent requests (~80) with alternating SetBit/SetRowAttr calls in batches of 512.
64 bit linux.

**Comment by tgruben** [comment]
This was fixed with the container type fix.
